services:
  - type: web
    name: plant-management-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: VITE_API_URL
        value: https://1cff-89-150-165-188.ngrok-free.app
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://1cff-89-150-165-188.ngrok-free.app/api/*
      - type: rewrite
        source: /watering-schedule/*
        destination: https://1cff-89-150-165-188.ngrok-free.app/watering-schedule/* 