services:
  - type: web
    name: plant-management-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend
      python run_migrations.py
    startCommand: |
      cd backend
      gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 50
    envVars:
      - key: DATABASE_URL
        value: postgresql://plant_db_user:sfz52a2WmKhXyYueaQaAScA7hspmcHqg@dpg-d0cqkbemcj7s73armf1g-a.frankfurt-postgres.render.com/plant_db
      - key: FRONTEND_URL
        value: https://plant-management-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: RENDER
        value: true
      - key: WEATHER_LOCATION
        value: Copenhagen
      - key: WEATHER_LAT
        value: 55.676098
      - key: WEATHER_LON
        value: 12.568337
      - key: WEATHER_API_URL
        value: https://api.open-meteo.com/v1/forecast

  - type: web
    name: plant-management-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://plant-management-backend.onrender.com
      - key: NODE_VERSION
        value: 20.11.1 