"""add_weather_forecast_model

Revision ID: 5cf44b53f2ea
Revises: ffbbe9c2e373
Create Date: 2025-04-14 14:29:35.331687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf44b53f2ea'
down_revision: Union[str, None] = 'ffbbe9c2e373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weather_forecast_id'), 'weather_forecast', ['id'], unique=False)
    op.create_unique_constraint('unique_weather', 'weather_forecast', ['timestamp', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_weather', 'weather_forecast', type_='unique')
    op.drop_index(op.f('ix_weather_forecast_id'), table_name='weather_forecast')
    # ### end Alembic commands ###
