"""fix_user_plants_sequence

Revision ID: ffbbe9c2e373
Revises: e5a31c7256df
Create Date: 2025-04-14 14:27:23.896642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffbbe9c2e373'
down_revision: Union[str, None] = 'e5a31c7256df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecast')
    op.alter_column('user_plants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_plants', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_plants_user_id_plant_id_key', 'user_plants', type_='unique')
    op.create_index(op.f('ix_user_plants_id'), 'user_plants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_plants_id'), table_name='user_plants')
    op.create_unique_constraint('user_plants_user_id_plant_id_key', 'user_plants', ['user_id', 'plant_id'])
    op.alter_column('user_plants', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_plants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('weather_forecast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precipitation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='weather_forecast_pkey')
    )
    # ### end Alembic commands ###
